_wandb:
    value:
        cli_version: 0.25.0
        e:
            u7a4f0fluadb9h0i64c9k0n7weqreqry:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "16106127360"
                codePath: run_vanilla_vs_gmm.py
                codePathLocal: run_vanilla_vs_gmm.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "449797640192"
                email: ar36@sanger.ac.uk
                executable: /Users/ar36/miniforge3/bin/python
                git:
                    commit: acd677d83d57644e8f3c295adf0ff46f53d6d88e
                    remote: https://github.com/AndreaRubbi/CellFlow.git
                host: mib120160s
                memory:
                    total: "19327352832"
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/ar36/Desktop/CellFlow/run_vanilla_vs_gmm.py
                python: CPython 3.12.10
                root: comparison_results
                startedAt: "2026-03-07T15:40:15.112520Z"
                writerId: u7a4f0fluadb9h0i64c9k0n7weqreqry
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 53
                - 54
            "2":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 53
                - 54
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.10
            "5": 0.25.0
            "6": 5.0.0
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 256
condition_embedding_dim:
    value: 256
conditioning:
    value: film
data_dim:
    value: 50
hidden_dims:
    value: 512x512x512
logits_hidden_dims:
    value:
        - 256
        - 256
lr:
    value: 0.0005
means_hidden_dims:
    value:
        - 256
        - 256
model_name:
    value: GMM CellFlow (Learned GMM source)
n_dev_perts:
    value: 21
n_test_perts:
    value: 53
n_train_perts:
    value: 31
num_iters:
    value: 15000
num_modes:
    value: 32
seed:
    value: 42
source_type:
    value: gmm
temperature:
    value: 0.3
variance:
    value: 0.05
