_wandb:
    value:
        cli_version: 0.25.0
        e:
            ltstpfvyz85bme4tles2q32ucxdbhux5:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "16106127360"
                codePath: run_combosciplex_vanilla_vs_gmm.py
                codePathLocal: run_combosciplex_vanilla_vs_gmm.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "454043000832"
                email: ar36@sanger.ac.uk
                executable: /Users/ar36/miniforge3/envs/cellflow/bin/python
                git:
                    commit: acd677d83d57644e8f3c295adf0ff46f53d6d88e
                    remote: https://github.com/AndreaRubbi/CellFlow.git
                host: mib120160s
                memory:
                    total: "19327352832"
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/ar36/Desktop/CellFlow/run_combosciplex_vanilla_vs_gmm.py
                python: CPython 3.12.13
                root: combosciplex_results
                startedAt: "2026-03-09T23:06:51.161563Z"
                writerId: ltstpfvyz85bme4tles2q32ucxdbhux5
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 53
                - 54
            "2":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 53
                - 54
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.13
            "5": 0.25.0
            "6": 5.3.0
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 256
condition_embedding_dim:
    value: 256
conditioning:
    value: film
fingerprint_dim:
    value: 1024
gmm_cooldown:
    value: 0
gmm_warmup:
    value: 0
hidden_dims:
    value: 512x512x512
lr:
    value: 0.0005
model_name:
    value: Vanilla CellFlow (Control source)
n_test_conds:
    value: 7
n_train_conds:
    value: 25
num_iters:
    value: 30000
probability_path_noise:
    value: 1.5
seed:
    value: 42
source_matching_weight:
    value: 0
source_type:
    value: gaussian
